-- Migration 003: True Learning Loop - Reflections Table
-- Creates table to store Claude's explicit learnings from each research cycle

-- Reflections table: Stores what Claude learned, biases identified, and adjustments made
CREATE TABLE IF NOT EXISTS reflections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  experiment_id UUID NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
  reflection_type VARCHAR(50) NOT NULL CHECK (reflection_type IN ('learned', 'bias_identified', 'adjustment_made')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for fast lookups by experiment
CREATE INDEX idx_reflections_experiment ON reflections(experiment_id);

-- Index for querying by type
CREATE INDEX idx_reflections_type ON reflections(reflection_type);

-- Enable Row Level Security
ALTER TABLE reflections ENABLE ROW LEVEL SECURITY;

-- Public read access (same as other tables)
CREATE POLICY "Reflections are publicly readable"
  ON reflections
  FOR SELECT
  USING (true);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE reflections;

-- Comments
COMMENT ON TABLE reflections IS 'Stores Claudes explicit learnings, identified biases, and adjustments from each research cycle';
COMMENT ON COLUMN reflections.reflection_type IS 'Type of reflection: learned, bias_identified, or adjustment_made';
COMMENT ON COLUMN reflections.content IS 'The actual reflection text generated by Claude';
